name: ALT Linux Build

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build software using docker
    strategy:
      matrix:
        alt-version: [ { dist: "alt:sisyphus", artifact: "sisyphus" } ]
        architecture: [ amd64 ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - run: docker build . --file Dockerfile --tag build-environment --build-arg USER_ID=$(id -u) --build-arg GROUP_ID=$(id -g) --build-arg DISTR=${{ matrix.alt-version.dist }} --build-arg ARCH=${{ matrix.architecture  }}

      - if: ${{ matrix.architecture == 'i386' }}
        run: docker run --privileged=true -i --log-driver=none -a stdin -a stdout -a stderr -v "$(pwd)":/app build-environment --platform linux/i386

      - if: ${{ matrix.architecture == 'amd64' }}
        run: docker run --privileged=true -i --log-driver=none -a stdin -a stdout -a stderr -v "$(pwd)":/app build-environment

      - uses: actions/upload-artifact@v3
        with:
          name: cgreen-${{ matrix.alt-version.artifact }}-${{ matrix.architecture }}
          path: /home/builder2/RPM/RPMS/x86_64/
